# Generated by Django 4.0.6 on 2022-08-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet', '0003_customer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.TextField(max_length=3, null=True),
        ),
    ]
