# Generated by Django 4.0.6 on 2022-08-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet', '0004_remove_account_account_type_alter_wallet_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.TextField(max_length=4, null=True),
        ),
    ]
