# Generated by Django 4.0.6 on 2022-08-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet', '0006_customer_pin_alter_wallet_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipts',
            name='transaction',
        ),
    ]
